name: "react-app: Run unit tests"

on: push

env:
  CI: true

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: My first step
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: nytimes-books
        run: npm ci
      - name: Run unit tests
        working-directory: nytimes-books
        run: npm test
