name: "NYTIMES unit tests"

on: push

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
        env:
          REACT_APP_NYTIMES_API_KEY: EPQfG6lAOJgoKSMq58JMRxSHooAQynA4
          REACT_APP_NYTIMES_BASE_URL: https://api.nytimes.com
